name: ohuseire_course
version: "1.0.0"
config-version: 2

profile: ohuseire_course

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  ohuseire_course:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      dimensions:
        +materialized: table
      facts:
        +materialized: table
      presentation:
        +materialized: view

seeds:
  ohuseire_course:
    +quote_columns: false
